const HTTP_OK = 200;
const HTTP_NOT_MODIFIED = 304;
const HTTP_BAD_REQUEST = 400;
const HTTP_UNAUTHORIZED = 401;
const HTTP_NOT_FOUND = 404;
const HTTP_VIOLATION_OF_RULE = 406;
const HTTP_CONFLICT = 409;
const HTTP_INTERNAL_ERROR = 500;

module.exports = {
  HTTP_OK,
  HTTP_NOT_MODIFIED,
  HTTP_BAD_REQUEST,
  HTTP_UNAUTHORIZED,
  HTTP_NOT_FOUND,
  HTTP_VIOLATION_OF_RULE,
  HTTP_CONFLICT,
  HTTP_INTERNAL_ERROR
};
